---
title: A Plot of Mtcars
author: Rob Wiederstein
date: '2021-02-10'
slug: []
categories:
  - R
tags:
  - shapefiles
lastmod: '2021-02-10T19:47:20-06:00'
keywords: ''
description: ''
comment: no
toc: no
autoCollapseToc: no
postMetaInFooter: no
hiddenFromHomePage: no
contentCopyright: no
reward: no
mathjax: no
mathjaxEnableSingleDollar: no
mathjaxEnableAutoNumber: no
hideHeaderAndFooter: no
flowchartDiagrams:
  enable: no
  options: ''
sequenceDiagrams:
  enable: no
  options: ''
output:
  blogdown::html_page:
    toc: true
---

The greatest challenge is starting.  The `mtcars` dataset is the default for demonstrating both code and plots.  

# Load libraries

Any project should begin with the loading of the necessary tools. Code block output is often messy with libraries in that warning messages regarding conflicts in the namespace are verbose.


```{r load-libraries, include = T, warning=F, error=F}
x <- c("dplyr", "magrittr", "kableExtra", "ggplot2")
lapply(x, library, character.only = T)
```

# Build a table

```{r}
data(mtcars)
mtcars$model <- row.names(mtcars)
rownames(mtcars) <- NULL
dplyr::filter(mtcars, cyl == 4) %>%
  select(model, mpg, cyl) %>%
  arrange(-mpg) %>%
  kableExtra::kbl()
```

# Make a plot

```{r make-plot, fig.align="center"}
mtcars$cyl <- factor(mtcars$cyl)
p <- ggplot(mtcars, aes(mpg, wt, group = cyl, color = cyl))
p <- p + geom_point()
p <- p + ggtitle("Mtcars")
p
```

